# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  if Vagrant.has_plugin?('vagrant-vbguest')
    config.vm.provider :virtualbox do
      config.vbguest.auto_update = false
    end
  end

  config.vm.define 'cv_app' do |app|
    app.vm.box = 'generic/ubuntu2204'
    app.vm.hostname = 'cv-app.local'
    app.vm.network 'forwarded_port', guest: 3000, host: 3000
    app.vm.network 'private_network', ip: '192.168.56.10'

    app.vm.provider 'virtualbox' do |vb|
      vb.name = 'cv-app.local'
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  config.vm.synced_folder '../webapp', '/vagrant/webapp', create: true

  config.vm.provision 'ansible_local' do |ansible|
    ansible.playbook = 'playbooks/run.yml'
    ansible.tags = 'install,check'
  end
end
